name=input("Enter the name:")
std=input("Enter the std:")
dob=input("Enter the dob:")
adm=input("Enter the adm number:")
group=input("Enter the blood group:")
school=input("Enter the school:")
phoneno=input("Enter the phone number:")
print("*"*50)
print("Identity Card")
print("Name             : "+name)
print("Std              : "+std)
print("DOb              : "+dob)
print("Admission number : "+adm)
print("Blood group      : "+group)
print("School           : "+school)
print("Phoneno          : "+phoneno)
print("*"*50)